package kz.halyqsoft.univercity.utils.excel;

/**
 * @author Omarbek Dinassil
 * @created 31.05.2017.
 */
public enum ExcelStyles {
	TITLE, TITLE_RIGHT, SUBTITLE_CENTER, SUBTITLE_LEFT, HEADER_BORDER_THIN, HEADER_LEFT, HEADER_RIGHT, HEADER_CENTER, HEADER, HEADER_VERTICAL, CONTENT_LEFT,
	CONTENT_CENTER, CONTENT_CENTER_WRAP, FOOTER, FOOTER_LEFT, TRANSCRIPT_STUDENT, TRANSCRIPT_HEADER_LEFT, TRANSCRIPT_BOLD_LEFT, TRANSCRIPT_LEFT, ORDER_BOLD_LEFT,
	ORDER_BOLD_CENTER, ORDER_CENTER, ITALIC, SUBTITLE_CENTER_WITH_BORDER, SUBTITLE_LEFT_WITH_BORDER, HEADER_CENTER_WITH_BORDER, TITLE_WITH_BORDER, TITLE_VERTICAL_WITH_BORDER,
	TITLE_VERTICAL_WITH_BORDER_LESS_GREEN, TITLE_VERTICAL_WITH_BORDER_PURPLE, TITLE_VERTICAL_WITH_BORDER_BLUE, TITLE_VERTICAL_WITH_BORDER_BROWN, TITLE_VERTICAL_WITH_BORDER_ORANGE,
	TITLE_VERTICAL_WITH_BORDER_VIOLET, TITLE_VERTICAL_WITH_BORDER_LESS_BLUE, TITLE_VERTICAL_WITH_BORDER_YELLOW, TITLE_VERTICAL_WITH_BORDER_GREEN, TITLE_VERTICAL_WITH_BORDER_LESS_ORANGE,
	TITLE_VERTICAL_WITH_BORDER_WRAP, TITLE_VERTICAL_WITH_BORDER_LEMON_CHIFFON, SUBTITLE_CENTER_WITH_BORDER_WRAP
}
