ALTER TABLE user_passport ADD COLUMN serial_number VARCHAR(255);

CREATE TABLE student_additional_information (
  id BIGINT NOT NULL ,
  student_id BIGINT NOT NULL,
  CONVICTION_AVAILABILITY BOOLEAN NOT NULL DEFAULT FALSE ,
  PERSONAL_COMPUTER_AVAILABILITY BOOLEAN NOT NULL DEFAULT FALSE,
  COMPUTER_SKILLS_AVAILABILITY BOOLEAN NOT NULL DEFAULT FALSE ,
  INFORMATION_SOURCE text,
  USE_AVAILABILITY BOOLEAN NOT NULL DEFAULT FALSE,
  CERTIFIED_COPY_ATTESTATE BOOLEAN NOT NULL DEFAULT FALSE ,
  CONTRACT_AVAILABILITY BOOLEAN NOT NULL DEFAULT FALSE ,
  PHOTO_AVAILABILITY BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE RESTRICT ON UPDATE RESTRICT
);


CREATE SEQUENCE s_student_additional_information MINVALUE 0 START WITH 1 NO CYCLE ;