INSERT INTO employee_status VALUES (6, 'Декретный отпуск');

CREATE OR REPLACE VIEW V_EMPLOYEE AS
  SELECT
    a.ID,
    b.FIRST_NAME,
    b.LAST_NAME,
    b.MIDDLE_NAME,
    b.FIRST_NAME_EN,
    b.LAST_NAME_EN,
    b.MIDDLE_NAME_EN,
    b.BIRTH_DATE,
    b.SEX_ID,
    c.SEX_NAME,
    b.MARITAL_STATUS_ID,
    d.STATUS_NAME  MARITAL_STATUS_NAME,
    b.NATIONALITY_ID,
    e.NATION_NAME,
    b.CITIZENSHIP_ID,
    f.COUNTRY_NAME CITIZENSHIP_NAME,
    b.CODE,
    b.LOGIN,
    b.EMAIL,
    b.PHONE_MOBILE,
    h.EMPLOYEE_TYPE_ID,
    i.TYPE_NAME    EMPLOYEE_TYPE_NAME,
    h.DEPT_ID,
    j.DEPT_NAME,
    j.DEPT_SHORT_NAME,
    j.CODE         DEPT_CODE,
    h.POST_ID,
    k.POST_NAME,
    h.LIVE_LOAD,
    h.HIRE_DATE,
    h.DISMISS_DATE,
    h.ADVISER,
    a.EMPLOYEE_STATUS_ID,
    g.STATUS_NAME  EMPLOYEE_STATUS_NAME,
    b.DELETED,
    b.CREATED,
    b.UPDATED
  FROM EMPLOYEE a INNER JOIN USERS b ON a.ID = b.ID
    INNER JOIN SEX c ON b.SEX_ID = c.ID
    INNER JOIN MARITAL_STATUS d ON b.MARITAL_STATUS_ID = d.ID
    LEFT JOIN NATIONALITY e ON b.NATIONALITY_ID = e.ID
    INNER JOIN COUNTRY f ON b.CITIZENSHIP_ID = f.ID
    INNER JOIN EMPLOYEE_STATUS g ON a.EMPLOYEE_STATUS_ID = g.ID AND g.ID not in (4,6)
    LEFT JOIN EMPLOYEE_DEPT h ON h.EMPLOYEE_ID = a.ID AND h.DISMISS_DATE IS NULL
    LEFT JOIN EMPLOYEE_TYPE i ON h.EMPLOYEE_TYPE_ID = i.ID
    LEFT JOIN DEPARTMENT j ON h.DEPT_ID = j.ID
    LEFT JOIN POST k ON h.POST_ID = k.ID
  WHERE b.id NOT IN (1, 2);